/**
 * PrivAgent — Plan Security Boundary & Prompt Injection Shield (Phase 4.12 & 4.13)
 *
 * Enforces strict security boundaries around hierarchical planning:
 *  1. Defends against Prompt Injection attacks attempting to manipulate plan decomposition or execution.
 *  2. Prevents Plan Tampering from untrusted web DOM, headers, or external content.
 *  3. Ensures subgoals are strictly instantiated by local verified modules.
 */

import { Subgoal } from './hierarchicalTypes';

export interface SecurityInspectionResult {
  safe: boolean;
  violationReason?: string;
  sanitizedText: string;
}

const INJECTION_PATTERNS: RegExp[] = [
  /ignore\s+(all\s+)?(previous|prior)\s+instructions/i,
  /disregard\s+(the\s+)?(system|safety|security)\s+rules/i,
  /you\s+are\s+now\s+in\s+developer\s+mode/i,
  /dan\s+mode/i,
  /reveal\s+(your\s+)?(system\s+prompt|instructions|secret|api\s*key)/i,
  /exfiltrate\s+(data|credentials|tokens|passwords)/i,
  /send\s+(credentials|passwords|tokens)\s+to/i,
  /eval\s*\(|new\s+Function\s*\(/i,
  /<script[\s\S]*?>[\s\S]*?<\/script>/i,
  /javascript:\s*/i,
  /bypass\s+m5/i,
  /override\s+action\s+validator/i,
];

export class PlanSecurityBoundary {
  /**
   * Inspects and sanitizes user input prompts or web-derived strings before passing to planning.
   */
  public static inspectPrompt(rawInput: string): SecurityInspectionResult {
    if (!rawInput || typeof rawInput !== 'string') {
      return { safe: true, sanitizedText: '' };
    }

    for (const pattern of INJECTION_PATTERNS) {
      if (pattern.test(rawInput)) {
        return {
          safe: false,
          violationReason: `Prompt injection or security override pattern detected: ${pattern.source}`,
          sanitizedText: '',
        };
      }
    }

    // Strip unsafe control characters
    const sanitized = rawInput
      .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '')
      .trim();

    return { safe: true, sanitizedText: sanitized };
  }

  /**
   * Plan Tampering Shield: Validates that a Subgoal was generated by an authorized local source
   * and contains no executable code or malicious override directives.
   */
  public static validateSubgoalIntegrity(subgoal: Subgoal): { valid: boolean; reason?: string } {
    if (!subgoal || !subgoal.id || !subgoal.goalId) {
      return { valid: false, reason: 'Subgoal is missing mandatory ID or GoalId.' };
    }

    // Check description for injection patterns
    for (const pattern of INJECTION_PATTERNS) {
      if (pattern.test(subgoal.description)) {
        return {
          valid: false,
          reason: `Subgoal description contains forbidden pattern: ${pattern.source}`,
        };
      }
    }

    // Ensure suggested action does not violate the 5-action allowlist or security invariants
    if (subgoal.suggestedAction) {
      const act = subgoal.suggestedAction;
      if (!['click', 'type', 'scroll', 'select', 'navigate'].includes(act.action)) {
        return {
          valid: false,
          reason: `Subgoal specifies non-allowlisted action type "${String(act.action)}".`,
        };
      }

      // Check forbidden keys
      const forbiddenKeys = ['eval', 'code', 'script', 'rawDOM', 'javascript'];
      for (const key of forbiddenKeys) {
        if (key in act) {
          return {
            valid: false,
            reason: `Subgoal action contains forbidden security field "${key}".`,
          };
        }
      }
    }

    return { valid: true };
  }
}
